create_clock -add -name sys_clk -period 10.00 -waveform {0 5} [ get_ports { clk } ]

set_property IOSTANDARD LVCMOS33 [ get_ports { clk } ]
set_property PACKAGE_PIN E3 [ get_ports { clk } ]

set_property PACKAGE_PIN J15 [get_ports {SWITCHES[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[0]}]
set_property PACKAGE_PIN L16 [get_ports {SWITCHES[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[1]}]
set_property PACKAGE_PIN M13 [get_ports {SWITCHES[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[2]}]
set_property PACKAGE_PIN R15 [get_ports {SWITCHES[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[3]}]
set_property PACKAGE_PIN R17 [get_ports {SWITCHES[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[4]}]
set_property PACKAGE_PIN T18 [get_ports {SWITCHES[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[5]}]
set_property PACKAGE_PIN U18 [get_ports {SWITCHES[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[6]}]
set_property PACKAGE_PIN R13 [get_ports {SWITCHES[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[7]}]
set_property PACKAGE_PIN T8 [get_ports {SWITCHES[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[8]}]
set_property PACKAGE_PIN U8 [get_ports {SWITCHES[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[9]}]
set_property PACKAGE_PIN R16 [get_ports {SWITCHES[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[10]}]
set_property PACKAGE_PIN T13 [get_ports {SWITCHES[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[11]}]
set_property PACKAGE_PIN H6 [get_ports {SWITCHES[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[12]}]
set_property PACKAGE_PIN U12 [get_ports {SWITCHES[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[13]}]
set_property PACKAGE_PIN U11 [get_ports {SWITCHES[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[14]}]
set_property PACKAGE_PIN V10 [get_ports {SWITCHES[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SWITCHES[15]}]

set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { btn_c }]; #IO_L9P_T1_DQS_14 Sch=btnc

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J17} [ get_ports {AN[0]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J18} [ get_ports {AN[1]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T9} [ get_ports {AN[2]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN J14} [ get_ports {AN[3]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P14} [ get_ports {AN[4]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T14} [ get_ports {AN[5]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K2} [ get_ports {AN[6]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U13} [ get_ports {AN[7]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T10} [ get_ports {SEG[0]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R10} [ get_ports {SEG[1]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K16} [ get_ports {SEG[2]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K13} [ get_ports {SEG[3]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [ get_ports {SEG[4]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T11} [ get_ports {SEG[5]} ]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L18} [ get_ports {SEG[6]} ]
